language: shell
os: linux
dist: bionic
services: docker

env:
  global:
  # To enable BuildKit, set the DOCKER_BUILDKIT environment variable to 1
  - DOCKER_BUILDKIT=1
  # Image tag
  - KC_IMAGE_TAG="latest"

before_install:
  - |
    echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
    if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.md$)|(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)|^(docs)/'
    then
      if [ -z "${TRAVIS_TAG}" ]; then
        echo "Only doc files were updated, not running the CI."
        exit
      fi
    fi

  # Install the latest Docker version (>= 19.03) in order to use BuildKit
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker version

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Pull the necessary docker images in advance
  - docker pull openjdk:11.0.7-jdk-slim-buster
  - if docker pull manaty/keycloak:${KC_IMAGE_TAG} > /dev/null; then echo "keycloak pulled up"; fi

script:
  - set -e

  # Build a keycloak image
  - docker build
    --tag manaty/keycloak:${KC_IMAGE_TAG}
    --build-arg BUILDKIT_INLINE_CACHE=1
    -f docker/Dockerfile ./docker

after_success:
  - docker tag manaty/keycloak:${KC_IMAGE_TAG} manaty/keycloak:10.0.2
  - docker push manaty/keycloak:10.0.2
  - docker push manaty/keycloak:${KC_IMAGE_TAG}

after_script:
  - docker images
