version: '3'

volumes:
  keycloak_data:
    driver: local

services:
  keycloak:
    image: manaty/keycloak
    container_name: keycloak
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data/keycloakdb
    environment:
      #PROXY_ADDRESS_FORWARDING: "true"   # Need to uncomment if keycloak server is behind proxy.
      KEYCLOAK_USER: [ADMIN_USERNAME]
      KEYCLOAK_PASSWORD: [ADMIN_PASSWORD]
    ports:
      - 8081:8080
